### ISSUE TITLE
Registo de end device na TTN ao criar novo sensor na aplicação

### ISSUE THREAD

**Issue by renatopanda** [Hernani-Diniz/Final#1]
Ao criar um novo sensor na aplicação web, este também deve ser registado automaticamente na TTN. Atualmente:
1. User preenche formulário com dados do novo sensor
2. Dados são validados (?)
3. Sensor.create() para inserir a entrada na base de dados (nova linha na tabela sensors)

Após o passo 3 (ou antes, ou até em paralelo), deve haver o registo desse mesmo sensor na TTN dentro da aplicação TTN que tiver sido criada para o efeito. Para isso, é necessário ler a documentação da API da TTN e fazer a chamada à API adequada usando a biblioteca axios (ou semelhante).

Links úteis:
* [TTN - Using the API ](https://www.thethingsindustries.com/docs/getting-started/api/)
  * Ler bem a documentação, pelos vistos o registo implica [4 chamadas (multi-step) à API pela ordem aí anunciada](https://www.thethingsindustries.com/docs/getting-started/api/#multi-step-actions), autenticada via NSXX API Key (já devem ter usado uma para ligar por MQTT, é registar outra com privilégios de registo de endpoints na app)
  * Tendo isto em conta, eu começava por tentar usar o curl (linha de comandos) ou o Postman para registar um sensor, com isso feito é simplesmente copiar e ajustar na API
* [TTN - End Device APIs](https://www.thethingsindustries.com/docs/reference/api/end_device/)
* [How to Make an HTTP Post Request using Node.js](https://attacomsian.com/blog/node-http-post-request)

**Comment by hedy44** [comment]
Sensores ja sao adicionados a ttn aquando do registo na aplicação
