### ISSUE TITLE
Carregar leituras da TTN para a aplicação web via MQTT

### ISSUE THREAD

**Issue by renatopanda** [Hernani-Diniz/Final#5]
Os sensores comunicam dados para a TTN, que os disponibiliza via MQTT. Assim, terá que existir um serviço extra (pode ser um script simples) que ligará por MQTT à TTN e ao receber uma nova mensagem, caso seja a leitura de um sensor, chamará um endpoint da API para reportar a nova leitura.

Passos possíveis:
- [ ] Criar script para subscrever a app TTN via MQTT (bónus se usar .env vars ou outro tipo de configuração não explícita no código)
- [ ] Criar um endpoint na BD da web app para comunicar uma nova leitura de temperatura e humidade do sensor X
- [ ] Adaptar o script para que ao receber uma mensagem esta seja passada para a web app (via API acima)
- [ ] Testar isto simulando um packet na TTN web console

**Comment by hedy44** [comment]
Ao fazer um uplink os valores ja sao recebidos na aplicação e guardados na BD e vistos na view sensorsread.hbs
